### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by solracsf** [githubjeka/tracker-issues#1]
@githubjeka 
While trying to ENABLE the module:

`Class 'm131023_165214_initial' not found`

When accessing a space with module activated:
```
yii\db\Exception
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'humhub.tracker_issue' doesn't exist
```
When trying to disable the module:
`Class 'uninstall' not found`

**Comment by githubjeka** [comment]
comment this row 
https://github.com/githubjeka/tracker-issues/blob/master/migrations/m131023_165214_initial.php#L3

and this
https://github.com/githubjeka/tracker-issues/blob/master/migrations/uninstall.php#L3

and reEnable module

**Comment by solracsf** [comment]
Nop, i still can't disable or uninstall it.
**EDIT:** I didn't see you last edit, it's OK now.

**Comment by githubjeka** [comment]
> upload all files to protected/modules/tracker/

Alright?

**Comment by solracsf** [comment]
Yes, all files uploaded.
It only works without those `namespaces`.

**Comment by solracsf** [comment]
After uninstall the module, my stream doesn't work anymore...and gives a `Error 500`.

```
{
    "url": "/dashboard/dashboard/stream?mode=normal",
    "status": 500,
    "response": {
        "name": "Exception",
        "message": "Could not get contents underlying object! - contentid: 420",
        "code": 0,
        "type": "yii\\base\\Exception",
        "file": "public/protected/humhub/modules/stream/actions/Stream.php",
        "line": 310,
        "stack-trace": [
            "#0 public/protected/humhub/modules/stream/actions/Stream.php(234): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
            "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
            "#2 public/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
            "#3 public/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
            "#4 public/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
            "#5 public/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
            "#6 public/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
            "#7 public/index.php(25): yii\\base\\Application->run()",
            "#8 {main}"
        ]
    }
}
```

**Comment by githubjeka** [comment]
namespace need to run test for me... Forgot to delete.

unninstall doesn't work yet
