### ISSUE TITLE
Error while uploading document

### ISSUE THREAD

**Issue by ChilliPipper** [githubjeka/tracker-issues#48]
I’m trying to upload a document and this is happening, I searched for that error but didn’t found anything. I’ve attached everything.

This is the complete error stack:

yii\base\UnknownPropertyException: Setting unknown property: tracker\models\Document::access_for_all in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set()
#1 /var/www/html/humhub/protected/modules/tracker_issue/controllers/services/DocumentCreator.php(97): yii\db\BaseActiveRecord->__set()
#2 /var/www/html/humhub/protected/modules/tracker_issue/controllers/DocumentController.php(99): tracker\controllers\services\DocumentCreator->create()
#3 [internal function]: tracker\controllers\DocumentController->actionCreate()
#4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#9 /var/www/html/humhub/index.php(25): yii\base\Application->run()
#10 {main}

![1](https://user-images.githubusercontent.com/19862280/142430337-620bdbf6-6dac-4dba-8902-61afe5167d77.jpg)
![2](https://user-images.githubusercontent.com/19862280/142430343-0fe657e8-34d2-40bd-b662-79573ea820e0.png)

**Comment by ArchBlood** [comment]
Have you tried removing `'access_for_all'` from the required field? From looking at the code `access_for_all` isn't really used much for it to be required in the first place. 🤔

I'm sure that there is a setting somewhere that hasn't been toggled that is causing the issue.

**Comment by githubjeka** [comment]
try to flush database cache

https://docs.humhub.org/docs/admin/console/
