### ISSUE TITLE
Installation problem on current HumHub master

### ISSUE THREAD

**Issue by buddh4** [githubjeka/tracker-issues#5]
When installing the module on the latest HumHub master I the following error is thrown:

```
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'humhub.#sql-47d_6e0' (errno: 150)' in /codebase/humhub/master/protected/vendor/yiisoft/yii2/db/Command.php:846 Stack trace: #0 /codebase/humhub/master/protected/vendor/yiisoft/yii2/db/Command.php(846): PDOStatement->execute() #1 /codebase/humhub/master/protected/vendor/yiisoft/yii2/db/Migration.php(428): yii\db\Command->execute() #2 /codebase/humhub/modules/tracker-issues/migrations/m170502_062820_tracker_links.php(24): yii\db\Migration->addForeignKey('<span class="st...', '<span class="st...', '<span class="st...', '<span class="st...', '...', 'CASCADE', 'CASCADE') #3 /codebase/humhub/master/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(654): m170502_062820_tracker_links->up() #4 /codebase/humhub/master/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp('<span class="st...') #5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp('<span class="nu...') #6 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array('[<span class="t...', '[<span class="n...') #7 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams('[]') #8 /codebase/humhub/master/protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('<span class="st...', '[]') #9 /codebase/humhub/master/protected/humhub/commands/MigrateController.php(193): yii\console\Controller->runAction('<span class="st...') #10 /codebase/humhub/master/protected/humhub/components/Module.php(267): humhub\commands\MigrateController::webMigrateUp('<span class="st...') #11 /codebase/humhub/master/protected/humhub/components/Module.php(196): humhub\components\Module->migrate() #12 /codebase/humhub/master/protected/humhub/modules/admin/controllers/ModuleController.php(83): humhub\components\Module->enable() #13 [internal function]: humhub\modules\admin\controllers\ModuleController->actionEnable() #14 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array('[<span class="t...', '[]') #15 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams('[<span class="s...') #16 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('<span class="st...', '[<span class="s...') #17 /codebase/humhub/master/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('<span class="st...', '[<span class="s...') #18 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /codebase/humhub/master/index.php(25): yii\base\Application->run() #20 {main} Next exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'humhub.#sql-47d_6e0' (errno: 150) The SQL being executed was: ALTER TABLE `tracker_links` ADD CONSTRAINT `fa_tracker_issue_parent` FOREIGN KEY (`parent_id`) REFERENCES `tracker_issue` (`id`) ON DELETE CASCADE ON UPDATE CASCADE' in /codebase/humhub/master/protected/vendor/yiisoft/yii2/db/Schema.php:636 Stack trace: #0 /codebase/humhub/master/protected/vendor/yiisoft/yii2/db/Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `tr...') #1 /codebase/humhub/master/protected/vendor/yiisoft/yii2/db/Migration.php(428): yii\db\Command->execute() #2 /codebase/humhub/modules/tracker-issues/migrations/m170502_062820_tracker_links.php(24): yii\db\Migration->addForeignKey('<span class="st...', '<span class="st...', '<span class="st...', '<span class="st...', '...', 'CASCADE', 'CASCADE') #3 /codebase/humhub/master/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(654): m170502_062820_tracker_links->up() #4 /codebase/humhub/master/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp('<span class="st...') #5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp('<span class="nu...') #6 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array('[<span class="t...', '[<span class="n...') #7 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams('[]') #8 /codebase/humhub/master/protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('<span class="st...', '[]') #9 /codebase/humhub/master/protected/humhub/commands/MigrateController.php(193): yii\console\Controller->runAction('<span class="st...') #10 /codebase/humhub/master/protected/humhub/components/Module.php(267): humhub\commands\MigrateController::webMigrateUp('<span class="st...') #11 /codebase/humhub/master/protected/humhub/components/Module.php(196): humhub\components\Module->migrate() #12 /codebase/humhub/master/protected/humhub/modules/admin/controllers/ModuleController.php(83): humhub\components\Module->enable() #13 [internal function]: humhub\modules\admin\controllers\ModuleController->actionEnable() #14 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array('[<span class="t...', '[]') #15 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams('[<span class="s...') #16 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('<span class="st...', '[<span class="s...') #17 /codebase/humhub/master/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('<span class="st...', '[<span class="s...') #18 /codebase/humhub/master/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /codebase/humhub/master/index.php(25): yii\base\Application->run() #20 {main} Additional Information: Array ( [0] => HY000 [1] => 1005 [2] => Can't create table 'humhub.#sql-47d_6e0' (errno: 150) )
```

**Comment by githubjeka** [comment]
Hmm...not reproduced

1. Install new master Humhub from github
![](http://image.prntscr.com/image/895c919bdb4c48e3bbb5b1ae776fff02.png)
2. Add my master version module to `humhub-empty\protected\modules\tracker-issues`
3. See in admin panel my module
![](http://image.prntscr.com/image/f845e5fea3094781a32e4a20a097145f.png)
4. Click "Enable"
![](http://image.prntscr.com/image/c5bf3b6b8c10485ab78cd46aa1318db4.png)

I can imagine that this error appears because tables from the first migration is missed. But why it is, I don't know. This is something by your local env ...

**Comment by buddh4** [comment]
Worked after manually reinstalling, strange don't see why it failed the first time.

**Comment by solracsf** [comment]
See https://github.com/githubjeka/tracker-issues/issues/7#issuecomment-299484654
