### ISSUE TITLE
Error on ENABLE, DISABLE and UNINSTALL

### ISSUE THREAD

**Issue by solracsf** [githubjeka/tracker-issues#7]
Click ENABLE, error:
```
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `dev_humhub`.`#sql-776_1730c` (errno: 150 "Foreign key constraint is incorrectly formed") in /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/db/Command.php:846
Stack trace: #0 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/db/Command.php(846): PDOStatement->execute()
#1 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/db/Migration.php(428): yii\db\Command->execute()
#2 /srv/users/dev/apps/dev-humhub/public/protected/modules/tracker/migrations/m170502_062820_tracker_links.php(23): yii\db\Migration->addForeignKey('fa_tracker_issu...', '{{%tracker_link...', 'parent_id', '{{%tracker_issu...', 'id', 'CASCADE', 'CASCADE')
#3 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(654): m170502_062820_tracker_links->up()
#4 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp('m170502_062820_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('up', Array)
#9 /srv/users/dev/apps/dev-humhub/public/protected/humhub/commands/MigrateController.php(193): yii\console\Controller->runAction('up')
#10 /srv/users/dev/apps/dev-humhub/public/protected/humhub/components/Module.php(267): humhub\commands\MigrateController::webMigrateUp('/srv/users/ekin...')
#11 /srv/users/dev/apps/dev-humhub/public/protected/humhub/components/Module.php(196): humhub\components\Module->migrate()
#12 /srv/users/dev/apps/dev-humhub/public/protected/humhub/modules/admin/controllers/ModuleController.php(83): humhub\components\Module->enable()
#13 [internal function]: humhub\modules\admin\controllers\ModuleController->actionEnable()
#14 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#16 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('enable', Array)
#17 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/module/en...', Array)
#18 /srv/users/dev/apps/dev-humhub/public/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /srv/users/dev/apps/dev-humhub/public/index.php(33): yii\base\Application->run()
#20 {main}
```

DISABLE and UNINSTALL states **table not found**, normal, table was not created at install/enable:
````
Can't create table `dev_humhub`.`#sql-776_1730c`
````

**Comment by githubjeka** [comment]
https://github.com/githubjeka/tracker-issues/issues/5

**Comment by solracsf** [comment]
I've tried to install it again (after full remove) same issue.

**(!!!)** This module has the same migration than `humhub-tasks` module so both can't be installed as the migration is already applied.

**m131023_165214_initial**, see
https://github.com/humhub/humhub-modules-tasks/blob/master/migrations/m131023_165214_initial.php

Fix it and this will be fixed.

**Comment by githubjeka** [comment]
Thanks
